server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./db/H2/data;'
    username: sa

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none       # (none, create, create-drop, update, validate)
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

jwt:
  secret: "signingKeyIsSigningKeyTokenAndTokenSecretIsSecretForSecret"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
